package
{
	public class Comments
	{
		
		public static const _positive:Array = new Array(
		"FTW!",
		"oh man where did i put my white raybans???",
		"yessssss!",
		"playin sax like a boss",
		"flagged as awesome content",
		"Play the song. Turn on the volume. Leave the house for 9 hours. Comeback and you will see an orgy under your window.",
		"If Aliens ever attacked us...He would save us all :)",
		"omgg so nice :D",
		"i could listen to this all day long",
		"i can hear this all day LOL :)",
		"the epic sax guy doesn't give a fuck",
		"Lol best song ever!",
		"chuck norris watches this 5 times a day",
		"OMG I fell asleep to this song awesome",
		"Is there an extended version?",
		"now this is what i call saxifying music",
		"I Think my head will explode xD﻿ I will never get this out of my head",
		"open a new tab, get on youtube watch any video that has talking in it and﻿ play this video slightly quieter... its amazing!",
		"When I listen to this long enough, I reach another level of existence where I can levitate, move objects with my mind, and have﻿ sax forever.",
		"I actually really love this song, it's one of the more bearable youtube loops",
		"this video﻿ is an epic tune",
		"not long﻿ enough",
		"Win.. just win.",
		"Looking for party music? here you﻿ go ! :)",
		"WARNING:﻿ CONTAINS SCENES OF A SAXUAL NATURE",
		"I i love this song no joke!!!﻿ thumbs up if you agree!!!!",
		"now that's﻿ HARDCORE",
		"hes saxing for﻿ freedom",
		"Chak Norris hört﻿ das lied 3 mal am Tag",
		"The video doesn't change. But﻿ you do..",
		"This﻿ song is more addictive then heroin! <3",
		"amazing!!! ﻿",
		"J'adooooooore *^*﻿ <3<3<3",
		"This song﻿ gave me an eargasm *-*",
		"i only﻿ made it 30 seconds before i came",
		"This needs to be﻿ the first video on YouTube with 1 billion views",
		"Best 10 h music ever﻿ :D",
		"MOLDOVA!!!!﻿",
		"Most epic song in the world! not﻿ f*cking u!!!",
		"Listening to this in music is the best﻿ :)",
		"I﻿ just love this so much it crosses all of the barriers of the mind",
		"i know what﻿ im goin to be for halloween",
		"osm I don't get tired of hearing﻿ this :D",
		"fuck yea﻿",
		"this should be﻿ banned for SAXual content.");
		
		public static const _neutral:Array = new Array(
		"Why???",
		"Ronaldinho1224﻿ sent me.",
		"I liked the part how he played the sax",
		"A seven second clip repeated for 10 hours? Simply amazing.",
		"._O",
		"lol",
		"challenge accepted",
		"rick roller + justin bieber = epic sax fail",
		"were do we get the notes",
		"The charity may be less than﻿ desirable as they seem to spend donated money on other projects rather than giving it to the children that need it. but the cause and the meaning behind it, is more than worth while. even if the numbers have been exaggerated, taking the life of one child is monstrous and for that alone this man should be stopped. Kony 2012",
		"Mum: \"Time for bed,\nMe: \"…Just one﻿ more video…….\"",
		"lol fuck you ron!! haha",
		"who want full version??",
		"ummmmmm ok?",
		"thumbs up if you saw the 10 hidden seconds of porn?",
		"sexsophona",
		"im in a plane going to japan and this is still goin on when i reached hawaii airport lol",
		"Are you saxy?",
		"Some say he is still dry humping...",
		"This is how he practices for his naked play time in the wood =]",
		"time to play league of legends while listening to 10 hour songs yes",
		"rest and resaxation?",
		"O_O moar thrust",
		"Oh... my... god... I think I'm in that part of youtube again -.-",
		"SO... MUCH... SAXUAL... CONTENT....",
		"Banananananana :P﻿",
		"sometimes at night i like to get﻿ naked, cover myself in baby oil,close my eyes,smile,and pretend that im a slug",
		"Anyone else noticing the guy with the sax?﻿",
		"can someone tell what song he﻿ plays the sax in?",
		"he plays the saxophone the whole﻿ clip ?",
		"I was going to listen to this for﻿ ten hours, but Then i took an arrow to the Knee...",
		"he's﻿ more famous than all of his band members",
		"can someone plz﻿ make a song out of this");
		
		public static const _negative:Array = new Array(
		"So not worth it",
		"skip to the end",
		"epic fail guy",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has been flagged as spam.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"This comment has received too many negative votes.",
		"Thats the moves he uses on your mothers",
		"I find the moment when he really blow in his saxo .",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Comment removed.",
		"Ur a troll if u watch this for﻿ 10 hours hahaha",
		"meh",
		"fml",
		"my pelvic thrust﻿ is so much better");
		
		public function Comments()
		{
		}
	}
}